<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyThuVienCNTP2" Class="DB_QLTVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-F6GMAH7\SQLEXPRESS;Initial Catalog=QuanLyThuVienCNTP2;User ID=sa" SettingsObjectName="BLL_DAL.Properties.Settings" SettingsPropertyName="QuanLyThuVienCNTP2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CHUDE_TAILIEU" Member="TAILIEUs" ThisKey="MaChuDe" OtherKey="MaChuDe" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.VITRI" Member="VITRIs">
    <Type Name="VITRI">
      <Column Name="MaViTri" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ke" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="VITRI_TAILIEU" Member="TAILIEUs" ThisKey="MaViTri" OtherKey="MaViTri" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PHIEUMUON" Member="CT_PHIEUMUONs">
    <Type Name="CT_PHIEUMUON">
      <Column Name="MaChiTietPhieuMuon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieuMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTraCT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PHIEUMUON_CT_PHIEUMUON" Member="PHIEUMUON" ThisKey="MaPhieuMuon" OtherKey="MaPhieuMuon" Type="PHIEUMUON" IsForeignKey="true" />
      <Association Name="TAILIEU_CT_PHIEUMUON" Member="TAILIEU" ThisKey="MaVach" OtherKey="MaVach" Type="TAILIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PHIEUNHAP" Member="CT_PHIEUNHAPs">
    <Type Name="CT_PHIEUNHAP">
      <Column Name="MaChiTietPhieuNhap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieuNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNhaCungCap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_CT_PHIEUNHAP" Member="NHACUNGCAP" ThisKey="MaNhaCungCap" OtherKey="MaNhaCungCap" Type="NHACUNGCAP" IsForeignKey="true" />
      <Association Name="PHIEUNHAP_CT_PHIEUNHAP" Member="PHIEUNHAP" ThisKey="MaPhieuNhap" OtherKey="MaPhieuNhap" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="TAILIEU_CT_PHIEUNHAP" Member="TAILIEU" ThisKey="MaVach" OtherKey="MaVach" Type="TAILIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PHIEUTRA" Member="CT_PHIEUTRAs">
    <Type Name="CT_PHIEUTRA">
      <Column Name="MaChiTietPhieuTra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieuTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaPhieuMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PHIEUMUON_CT_PHIEUTRA" Member="PHIEUMUON" ThisKey="MaPhieuTra" OtherKey="MaPhieuMuon" Type="PHIEUMUON" IsForeignKey="true" />
      <Association Name="PHIEUTRA_CT_PHIEUTRA" Member="PHIEUTRA" ThisKey="MaPhieuTra" OtherKey="MaPhieuTra" Type="PHIEUTRA" IsForeignKey="true" />
      <Association Name="TAILIEU_CT_PHIEUTRA" Member="TAILIEU" ThisKey="MaVach" OtherKey="MaVach" Type="TAILIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_XULYVIPHAM" Member="CT_XULYVIPHAMs">
    <Type Name="CT_XULYVIPHAM">
      <Column Name="MaChiTietXuLyViPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaXuLyViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TienBoiThuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LOAIVIPHAM_CT_XULYVIPHAM" Member="LOAIVIPHAM" ThisKey="MaLoaiViPham" OtherKey="MaLoaiViPham" Type="LOAIVIPHAM" IsForeignKey="true" />
      <Association Name="PHIEUXULYVIPHAM_CT_XULYVIPHAM" Member="PHIEUXULYVIPHAM" ThisKey="MaXuLyViPham" OtherKey="MaXuLyViPham" Type="PHIEUXULYVIPHAM" IsForeignKey="true" />
      <Association Name="TAILIEU_CT_XULYVIPHAM" Member="TAILIEU" ThisKey="MaVach" OtherKey="MaVach" Type="TAILIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCGIA" Member="DOCGIAs">
    <Type Name="DOCGIA">
      <Column Name="MaTheThuVien" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiDocGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenDocGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HanSuDungTheThuVien" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrangTheThuVien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLamThe" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DOCGIA_PHIEUMUON" Member="PHIEUMUONs" ThisKey="MaTheThuVien" OtherKey="MaTheThuVien" Type="PHIEUMUON" />
      <Association Name="LOAIDOCGIA_DOCGIA" Member="LOAIDOCGIA" ThisKey="MaLoaiDocGia" OtherKey="MaLoaiDocGia" Type="LOAIDOCGIA" IsForeignKey="true" />
      <Association Name="NGANH_DOCGIA" Member="NGANH" ThisKey="MaNganh" OtherKey="MaNganh" Type="NGANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HINHTHUCXULY" Member="HINHTHUCXULies">
    <Type Name="HINHTHUCXULY">
      <Column Name="MaHinhThucXuLy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhiBoiThuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HINHTHUCXULY_LOAIVIPHAM" Member="LOAIVIPHAMs" ThisKey="MaHinhThucXuLy" OtherKey="MaHinhThucXuLy" Type="LOAIVIPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MaKhoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KHOA_NGANH" Member="NGANHs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="NGANH" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIDOCGIA" Member="LOAIDOCGIAs">
    <Type Name="LOAIDOCGIA">
      <Column Name="MaLoaiDocGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiDocGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAIDOCGIA_DOCGIA" Member="DOCGIAs" ThisKey="MaLoaiDocGia" OtherKey="MaLoaiDocGia" Type="DOCGIA" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINHANVIEN" Member="LOAINHANVIENs">
    <Type Name="LOAINHANVIEN">
      <Column Name="MaLoaiNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="NHANVIENs" ThisKey="MaLoaiNhanVien" OtherKey="MaLoaiNhanVien" Type="NHANVIEN" />
      <Association Name="LOAINHANVIEN_PHANQUYEN" Member="PHANQUYENs" ThisKey="MaLoaiNhanVien" OtherKey="MaLoaiNhanVien" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITAILIEU" Member="LOAITAILIEUs">
    <Type Name="LOAITAILIEU">
      <Column Name="MaLoaiTaiLieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LOAITAILIEU_TAILIEU" Member="TAILIEUs" ThisKey="MaLoaiTaiLieu" OtherKey="MaLoaiTaiLieu" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITINTUC" Member="LOAITINTUCs">
    <Type Name="LOAITINTUC">
      <Column Name="MaLoaiTinTuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMaLoaiTinTuc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="LOAITINTUC_TINTUC" Member="TINTUCs" ThisKey="MaLoaiTinTuc" OtherKey="MaLoaiTinTuc" Type="TINTUC" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIVIPHAM" Member="LOAIVIPHAMs">
    <Type Name="LOAIVIPHAM">
      <Column Name="MaLoaiViPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiViPham" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaHinhThucXuLy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAIVIPHAM_CT_XULYVIPHAM" Member="CT_XULYVIPHAMs" ThisKey="MaLoaiViPham" OtherKey="MaLoaiViPham" Type="CT_XULYVIPHAM" />
      <Association Name="HINHTHUCXULY_LOAIVIPHAM" Member="HINHTHUCXULY" ThisKey="MaHinhThucXuLy" OtherKey="MaHinhThucXuLy" Type="HINHTHUCXULY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MANHINH" Member="MANHINHs">
    <Type Name="MANHINH">
      <Column Name="MaManHinh" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="PHANQUYENs" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.NGANH" Member="NGANHs">
    <Type Name="NGANH">
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NGANH_DOCGIA" Member="DOCGIAs" ThisKey="MaNganh" OtherKey="MaNganh" Type="DOCGIA" />
      <Association Name="KHOA_NGANH" Member="KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGONNGU" Member="NGONNGUs">
    <Type Name="NGONNGU">
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NGONNGU_TAILIEU" Member="TAILIEUs" ThisKey="MaNgonNgu" OtherKey="MaNgonNgu" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNhaCungCap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhaCungCap" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_CT_PHIEUNHAP" Member="CT_PHIEUNHAPs" ThisKey="MaNhaCungCap" OtherKey="MaNhaCungCap" Type="CT_PHIEUNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangTK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHANVIEN_PHIEUMUON" Member="PHIEUMUONs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHIEUMUON" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHIEUNHAP" />
      <Association Name="NHANVIEN_PHIEUTRA" Member="PHIEUTRAs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHIEUTRA" />
      <Association Name="NHANVIEN_PHIEUXULYVIPHAM" Member="PHIEUXULYVIPHAMs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHIEUXULYVIPHAM" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="LOAINHANVIEN" ThisKey="MaLoaiNhanVien" OtherKey="MaLoaiNhanVien" Type="LOAINHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAXUATBAN" Member="NHAXUATBANs">
    <Type Name="NHAXUATBAN">
      <Column Name="MaNhaXuatBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhaXuatBan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NHAXUATBAN_TAILIEU" Member="TAILIEUs" ThisKey="MaNhaXuatBan" OtherKey="MaNhaXuatBan" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MaLoaiNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAINHANVIEN_PHANQUYEN" Member="LOAINHANVIEN" ThisKey="MaLoaiNhanVien" OtherKey="MaLoaiNhanVien" Type="LOAINHANVIEN" IsForeignKey="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="MANHINH" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="MANHINH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUMUON" Member="PHIEUMUONs">
    <Type Name="PHIEUMUON">
      <Column Name="MaPhieuMuon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTheThuVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiHanMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoSachMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhiCoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PHIEUMUON_CT_PHIEUMUON" Member="CT_PHIEUMUONs" ThisKey="MaPhieuMuon" OtherKey="MaPhieuMuon" Type="CT_PHIEUMUON" />
      <Association Name="PHIEUMUON_CT_PHIEUTRA" Member="CT_PHIEUTRAs" ThisKey="MaPhieuMuon" OtherKey="MaPhieuTra" Type="CT_PHIEUTRA" />
      <Association Name="DOCGIA_PHIEUMUON" Member="DOCGIA" ThisKey="MaTheThuVien" OtherKey="MaTheThuVien" Type="DOCGIA" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUMUON" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="MaPhieuNhap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CT_PHIEUNHAP" Member="CT_PHIEUNHAPs" ThisKey="MaPhieuNhap" OtherKey="MaPhieuNhap" Type="CT_PHIEUNHAP" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTRA" Member="PHIEUTRAs">
    <Type Name="PHIEUTRA">
      <Column Name="MaPhieuTra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongSachTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHIEUTRA_CT_PHIEUTRA" Member="CT_PHIEUTRAs" ThisKey="MaPhieuTra" OtherKey="MaPhieuTra" Type="CT_PHIEUTRA" />
      <Association Name="PHIEUTRA_PHIEUXULYVIPHAM" Member="PHIEUXULYVIPHAMs" ThisKey="MaPhieuTra" OtherKey="MaPhieuTra" Type="PHIEUXULYVIPHAM" />
      <Association Name="NHANVIEN_PHIEUTRA" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUXULYVIPHAM" Member="PHIEUXULYVIPHAMs">
    <Type Name="PHIEUXULYVIPHAM">
      <Column Name="MaXuLyViPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieuTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TongTienBoiThuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHIEUXULYVIPHAM_CT_XULYVIPHAM" Member="CT_XULYVIPHAMs" ThisKey="MaXuLyViPham" OtherKey="MaXuLyViPham" Type="CT_XULYVIPHAM" />
      <Association Name="NHANVIEN_PHIEUXULYVIPHAM" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUTRA_PHIEUXULYVIPHAM" Member="PHIEUTRA" ThisKey="MaPhieuTra" OtherKey="MaPhieuTra" Type="PHIEUTRA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TACGIA_TAILIEU" Member="TAILIEUs" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="TAILIEU" />
    </Type>
  </Table>
  <Table Name="dbo.TAILIEU" Member="TAILIEUs">
    <Type Name="TAILIEU">
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDauTaiLieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhaXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThongTinTaiLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaViTri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TAILIEU_CT_PHIEUMUON" Member="CT_PHIEUMUONs" ThisKey="MaVach" OtherKey="MaVach" Type="CT_PHIEUMUON" />
      <Association Name="TAILIEU_CT_PHIEUNHAP" Member="CT_PHIEUNHAPs" ThisKey="MaVach" OtherKey="MaVach" Type="CT_PHIEUNHAP" />
      <Association Name="TAILIEU_CT_PHIEUTRA" Member="CT_PHIEUTRAs" ThisKey="MaVach" OtherKey="MaVach" Type="CT_PHIEUTRA" />
      <Association Name="TAILIEU_CT_XULYVIPHAM" Member="CT_XULYVIPHAMs" ThisKey="MaVach" OtherKey="MaVach" Type="CT_XULYVIPHAM" />
      <Association Name="CHUDE_TAILIEU" Member="CHUDE" ThisKey="MaChuDe" OtherKey="MaChuDe" Type="CHUDE" IsForeignKey="true" />
      <Association Name="LOAITAILIEU_TAILIEU" Member="LOAITAILIEU" ThisKey="MaLoaiTaiLieu" OtherKey="MaLoaiTaiLieu" Type="LOAITAILIEU" IsForeignKey="true" />
      <Association Name="NGONNGU_TAILIEU" Member="NGONNGU" ThisKey="MaNgonNgu" OtherKey="MaNgonNgu" Type="NGONNGU" IsForeignKey="true" />
      <Association Name="NHAXUATBAN_TAILIEU" Member="NHAXUATBAN" ThisKey="MaNhaXuatBan" OtherKey="MaNhaXuatBan" Type="NHAXUATBAN" IsForeignKey="true" />
      <Association Name="TACGIA_TAILIEU" Member="TACGIA" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="TACGIA" IsForeignKey="true" />
      <Association Name="VITRI_TAILIEU" Member="VITRI" ThisKey="MaViTri" OtherKey="MaViTri" Type="VITRI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINTUC" Member="TINTUCs">
    <Type Name="TINTUC">
      <Column Name="MaTinTuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTinTuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTaNgan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuongLuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HienThiTrangChu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="LOAITINTUC_TINTUC" Member="LOAITINTUC" ThisKey="MaLoaiTinTuc" OtherKey="MaLoaiTinTuc" Type="LOAITINTUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_DOCGIA" Member="VW_DOCGIAs">
    <Type Name="VW_DOCGIA">
      <Column Name="Expr3" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTheThuVien" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiDocGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenDocGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HanSuDungTheThuVien" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrangTheThuVien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLamThe" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TINTUC" Member="VW_TINTUCs">
    <Type Name="VW_TINTUC">
      <Column Name="MaTinTuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiTinTuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTaNgan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuongLuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HienThiTrangChu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TenMaLoaiTinTuc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_NHANVIEN" Member="VW_NHANVIENs">
    <Type Name="VW_NHANVIEN">
      <Column Name="TenLoaiNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangTK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TAILIEU" Member="VW_TAILIEUs">
    <Type Name="VW_TAILIEU">
      <Column Name="Expr1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNhaXuatBan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ke" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expr3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenLoaiTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDauTaiLieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhaXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThongTinTaiLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaViTri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TAILIEUCUNGCHUDE" Member="VW_TAILIEUCUNGCHUDEs">
    <Type Name="VW_TAILIEUCUNGCHUDE">
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TAILIEUCUNGTACGIA" Member="VW_TAILIEUCUNGTACGIAs">
    <Type Name="VW_TAILIEUCUNGTACGIA">
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TAILIEUDAMUON" Member="VW_TAILIEUDAMUONs">
    <Type Name="VW_TAILIEUDAMUON">
      <Column Name="MaChiTietPhieuTra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaPhieuTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhieuMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongSachTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChiTietPhieuMuon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expr2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTraCT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Expr3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expr4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaTheThuVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expr5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiHanMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoSachMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhiCoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenNhaXuatBan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ke" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenLoaiTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Expr7" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDauTaiLieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhaXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThongTinTaiLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaViTri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expr6" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_TAILIEUDANGMUON" Member="VW_TAILIEUDANGMUONs">
    <Type Name="VW_TAILIEUDANGMUON">
      <Column Name="Expr1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaTheThuVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiHanMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoSachMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhiCoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaChiTietPhieuMuon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaPhieuMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangTraCT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TenNhaXuatBan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ke" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenLoaiTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaVach" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDauTaiLieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhaXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThongTinTaiLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaViTri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>